# Chapter 2

Creating a simple neural network using the MNIST dataset.

In [15]:
from tensorflow.keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [16]:
# Inspect the training data
train_images.shape

(60000, 28, 28)

In [17]:
# Check number of axes of the tensor train_images
train_images.ndim

3

In [18]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [19]:
# Inspect the test data
test_images.shape

(10000, 28, 28)

In [20]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [22]:
# Instantiate the model
model = Sequential()

# Build the layers
model.add(Dense(512, activation='relu', input_shape=(28 * 28,)))
model.add(Dense(10, activation='softmax'))

In [23]:
# Compile the model
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [24]:
# Preparing the image data
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [25]:
from tensorflow.keras.utils import to_categorical

# Encode the labels
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [26]:
# Fit the model
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 12s 208us/sample - loss: 0.2551 - accuracy: 0.9266
Epoch 2/5
60000/60000 [==============================] - 12s 194us/sample - loss: 0.1035 - accuracy: 0.9693
Epoch 3/5
60000/60000 [==============================] - 11s 182us/sample - loss: 0.0683 - accuracy: 0.9794
Epoch 4/5
60000/60000 [==============================] - 11s 186us/sample - loss: 0.0493 - accuracy: 0.9849- l - E
Epoch 5/5
60000/60000 [==============================] - 11s 183us/sample - loss: 0.0383 - accuracy: 0.9883


In [27]:
# Check how model performs on test set
test_loss, test_acc = model.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/10000 [==============================] - 2s 176us/sample - loss: 0.0655 - accuracy: 0.9817
test_acc: 0.9817


In [33]:
import numpy as np

In [34]:
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32,10))

In [37]:
x.shape

(64, 3, 32, 10)

In [38]:
y.shape

(32, 10)

In [40]:
z = np.maximum(x, y)

In [42]:
z.shape

(64, 3, 32, 10)

In [43]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])